### ISSUE TITLE
cuidado com o nome e marca comercial

### ISSUE THREAD

**Issue by ghost** [zekicarvalho/Eletrogenda#17]
Oi @zekicarvalho.

O termo 'electron' é proprietário(copyright) apesar da tecnologia electron ser aberta. temos que ter ao meu ver cuidado com o nome e marca comercial, para que o GitHub não desative esse repositório ou a sua conta ou a minha conta.

Nisso, pensei no nome "calen" para a abrevição de calendário eletrónico(na verdade é um neologismo da palavra eletrogenda). Ou a segunda opção seria mais direta: "genda"(que é a redução da palavra agenda e do eletrogenda). Pensei na segunda opção, pois é fácil de lembrar nomes curtos de pessoas ou coisas.

Faz sentido deixar o repo como calen em vez de eletrogenda? acha que ao mudar o nome ficaria melhor? ou que isso que falei (da minha preocupação do nome e marca electron ser comercial) faz sentido?

**Comment by zekicarvalho** [comment]
@nichdemos eu prefiro alterar, mas não por esses motivos de Copyright e sim porque eu achava esse nome estranho mesmo. Vou seguir com Calen.

**Comment by ghost** [comment]
Oi @zekicarvalho, brigadão mano tamo junto ^^
