### ISSUE TITLE
boa prática no desenvolvimento de software

### ISSUE THREAD

**Issue by ghost** [zekicarvalho/Eletrogenda#20]
Oi @zekicarvalho, como vai?

uma boa prática no desenvolvimento de software é abrir uma pull-request e debater na issue. Abrir essa issue para falar dos seguintes pull-requests: 
- [atualizando path do app: Calen](https://github.com/zekicarvalho/Calen/pull/19): atualizei aqui os caminhos até a pasta src por boa prática.
- [adicionando descricao no repo através do read-me](https://github.com/zekicarvalho/Calen/pull/18): aqui eu atualizei a descrição, é algo simples e talvez seja adicionado ou não.

o que pensa desses pull-requests iniciais?

**Comment by zekicarvalho** [comment]
Gostei bastante, foram aprovadas.

**Comment by ghost** [comment]
@zekicarvalho  tamo junto!
